# Travis CI config for AppStream

language: c
sudo: required
dist: trusty

services:
  - docker

compiler:
  - gcc
  #- clang -- see https://llvm.org/bugs/show_bug.cgi?id=23529

before_script:
  - docker build -t appstream -f tests/ci/Dockerfile .
  - if [ "$CC" = "clang" ]; then export CVENDOR="clang" CXX="clang" CC="clang"; fi
  - if [ "$CC" = "gcc" ]; then export CVENDOR="gcc" CXX="g++" CC="gcc"; fi

script:
  - docker run -t -e COMPILER_VENDOR=$CVENDOR -e CC=$CC -e CXX=$CXX -v `pwd`:/build appstream
    ./tests/ci/build_and_test.sh
